name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            artifact_name: noviy_nocd-windows
            asset_path: target/release/noviy_nocd.exe
          - os: ubuntu-latest
            artifact_name: noviy_nocd-linux
            asset_path: target/release/noviy_nocd

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Rust cache
      uses: swatinem/rust-cache@v2

    - name: Build
      run: cargo build --release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.asset_path }}
        if-no-files-found: error